move_to_height:
  target:
    entity:
      integration: desky_desk
      domain: cover
  fields:
    height:
      required: true
      example: 110
      selector:
        number:
          min: 60
          max: 130
          step: 0.1
          unit_of_measurement: cm
          mode: box

set_height_limit:
  target:
    entity:
      integration: desky_desk
      domain: cover
  fields:
    limit:
      required: true
      example: upper
      selector:
        select:
          translation_key: limit
          options:
            - upper
            - lower
    height:
      required: true
      example: 120
      selector:
        number:
          min: 60
          max: 124
          step: 0.1
          unit_of_measurement: cm
          mode: box

clear_height_limits:
  target:
    entity:
      integration: desky_desk
      domain: cover
