name: HACS Action
permissions:
  contents: read

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug - Check repository structure
        run: |
          echo "Repository root:"
          ls -la
          echo ""
          echo "custom_components directory:"
          ls -la custom_components/
          echo ""
          echo "Integration directory:"
          ls -la custom_components/desky_desk/
          echo ""
          echo "Manifest content:"
          cat custom_components/desky_desk/manifest.json
          echo ""
          echo "hacs.json content:"
          cat hacs.json

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: "integration"
          ignore: "brands"