name: Lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          python-version: "3.13"
          activate-environment: true
      - name: Install dependencies
        run: |
          uv pip install -r requirements_test_min.txt
          uv pip install -r <(python script/ha_test_requirements.py)
      - name: ruff check
        run: ruff check --output-format=github .
      - name: ruff format
        run: ruff format --check .
      - name: mypy
        run: mypy
